esphome:
  name: eustaquio

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
# api:
#   password: ""

ota:
  password: !secret eustaquio_ota

wifi:
  networks:
    - ssid: "JMC  INTRANET"
      password: !secret jmcintranet
    - ssid: "sercommBB2522"
      password: !secret sercomm
    - ssid: "COSMOPOLITAN"
      password: !secret cosmo_elche
    - ssid: "WIFI_SANITAT"
      password: !secret hospital_general
    - ssid: "Ortices"
      password: !secret oficina_ortices
    - ssid: "JM.Wifi"
      password: !secret oficina_padre   
    - ssid: "Vicenteiph"
      password: !secret vicenteiph
    - ssid: "iPhoneXdeSol"
      password: !secret sol14
      
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Eustaquio32 Fallback Hotspot"
    password: !secret fallback_pw


web_server:
  port: 80
  version: 2

mqtt:
  broker: !secret mqtt_broker
  discovery_prefix: homeassistant_vic_mac


captive_portal:
    

switch:
  - platform: template
    name: "Interruptor"
    optimistic: true
    icon: "mdi:restart"

i2c:

bme680_bsec:

sensor:
  - platform: bme680_bsec
    temperature:
      name: "BME680 Temperature"
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    iaq:
      name: "BME680 IAQ"
      id: iaq
    co2_equivalent:
      name: "BME680 CO2 Equivalent"
    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "BME680 IAQ Accuracy"

  - platform: template
    name: "BME680 IAQ Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremely polluted"};
      }
      else {
        return {"error"};
      }